### PR TITLE
Add window command

### PR DESCRIPTION
**Pull request by casey**
In the spirit of iterative development, this adds a `window` command that does nothing but open a window. We can make it useful later.

I think I'll try to add a test too.

### CODE REVIEW

**Comment by casey** [comment]
Watching the build on CI, I'm wondering if we should make this an optional feature. `bevy` pulls in a bunch of dependencies. But whatever, maybe that's a question for later. I made it build on CI, but disabled the test because it doesn't pass.

**Review by terror — APPROVED** [review]
Code looks good, works on my end. Compiling this took some time though :/

**Comment by casey** [comment]
Yeah, the long compilation time is a bummer. I just pushed a diff that makes `bevy` an optional dependency.

**Comment by casey** [comment]
Take another look and tell me what you think. I was trying to get the tests to run on CI under Linux, but gave up, since MacOS just works, and it's unlikely that we'll write platform specific code. We can always try to get them running on Linux later. To clean up tests that check for colored output, I added `atty`, to check if stderr is a terminal, but also a check for CLICOLOR_FORCE to override it for tests. (It's not widely used, but it's a [proposed standard](https://bixense.com/clicolors/).)

**Pull request merged**
