### PR TITLE
Refactor state

### PR DESCRIPTION
**Pull request by terror**

### CODE REVIEW

**Comment by casey** [comment]
Looks great! I pushed a change that changes the matrix to `DMatrix<Vector3<u8>>`. We aren't using alpha channels, so I didn't include them. Surprisingly there were almost no code changes required.

I started working on an `assert_output_eq` that we can use to deduplicate the tests, but had to go somewhere before I could finish it, so I pushed the broken version to the branch 😅

**Comment by casey** [comment]
Just pushed fixed tests. I just wrote the PNM generation code from scratch, so the output would look nice for tests.

**Comment by terror** [comment]
@casey Re-wrote some more filters using the new state. Still need to write integration tests + implement `Pixelate`. Let me know if you can think of better ways to right these

**Comment by casey** [comment]
These look good. We should get this into a mergable state, and maybe leave more improvements to another PR, to keep it from being outstanding for too long.

**Comment by casey** [comment]
I renamed `generate` to `resize`, in an effort to stick closer to nalgebra's terminology.

**Comment by casey** [comment]
@terror I just removed the pixelate filter, since we need to rewrite it anyways. What do you think getting this in, and worrying about pixelate later?

**Comment by terror** [comment]
> @terror I just removed the pixelate filter, since we need to rewrite it anyways. What do you think getting this in, and worrying about pixelate later?

Yep that's fine, did you want to review this fully before it gets merged?

**Comment by casey** [comment]
I just refactored a bit, to clean things up. `modulus` is now `mod` because
I kept misspelling it. It's a bit weird, because it operates column major,
but the closer we hew to how nalegbra works the better, I think. Take a
look and feel free to merge if you like it.

**Pull request merged**
