### PR TITLE
Loop

### PR DESCRIPTION
**Pull request by casey**
Depends on #51. Adds a `loop` command, which just loops forever.

Since degenerate is like a tiny computer, I used computer terminology. The `program` is the sequence of commands that are being run, and the `program_counter` is the the index of the next command to run. On a physical CPU, the program counter (also called the instruction pointer) is the address of the next instruction to run.

I did `cargo run square print loop` and it just hung, so I added the `verbose` command, which toggles the verbosity level, and makes it print the command its running and the program counter. Then I realized that I just didn't resize first.

I need to add tests.

### CODE REVIEW

**Comment by casey** [comment]
@terror Not ready to review, but it's shaping up to be a sweet little computer.

**Comment by casey** [comment]
@terror What do you think about turning this into a proper stack-based language like [forth](https://en.wikipedia.org/wiki/Forth_(programming_language))?

For example, `resize:10:20` would then be `10 20 resize` and `for:2` would be `2 for`. I think that it would be more flexible, and we could add a bunch of powerful stack manipulation operators.

**Comment by casey** [comment]
I'm actually also thinking that we should get rid of the `Command` type and just use strings. The primary reason we're using an enum instead of strings is to parse things like `resize:1:2` into a strongly typed value. However, if we make everything stack-based, we don't need to do that, and we can keep things as strings, which will have some benefits: no need to parse anything, can just match strings with `match arg { … }`, and error messages will be better, since we can print out whatever the user typed.

**Comment by terror** [comment]
> @terror What do you think about turning this into a proper stack-based language like [forth](https://en.wikipedia.org/wiki/Forth_(programming_language))?
> 
> For example, `resize:10:20` would then be `10 20 resize` and `for:2` would be `2 for`. I think that it would be more flexible, and we could add a bunch of powerful stack manipulation operators.

100% down for that, besides the syntax, it would allow for the additions of stack operations such as `rot`, `dup`, `over` etc which could be nice to have. We could also just iterate over individual tokens and match on those instead of parsing them into a type

**Comment by casey** [comment]
This is ready to go. It's shaping up to be a nice little computer! We should leave the stack stuff to another PR.

**Comment by casey** [comment]
I also started using `row col` consistently. Even though nalgebra is column-major,  it always puts row first and column second when addressing and in function arguments.

**Review by terror — APPROVED** [review]
lgtm

**Pull request merged**
