### PR TITLE
Add an image test for the circle filter

### PR DESCRIPTION
**Pull request by casey**
Adds an image test, a la #43. This needs to be improved, but gives the general idea. To do:

- [ ] Generate the tests using a build script, one for every png in the images directory

### CODE REVIEW

**Comment by casey** [comment]
I tried using git LFS. Not sure if we should actually do this, since LFS is annoying. Case in point, LFS files aren't checked out in the tests.

**Comment by casey** [comment]
LFS is weird and annoying, so I removed it.

**Comment by casey** [comment]
@terror I think this is ready to review. If we want, we can convert more tests to image tests, or improve how they're run in another PR. (For example by turning them all into separate tests, possibly generated by a build script.)

**Review by terror — APPROVED** [review]
Looks good!

**Comment by terror** [comment]
> @terror I think this is ready to review. If we want, we can convert more tests to image tests, or improve how they're run in another PR. (For example by turning them all into separate tests, possibly generated by a build script.)

Agreed. This is a good first implementation, improving on it later is fine

**Pull request merged**
