### PR TITLE
Add rotate command

### PR DESCRIPTION
**Pull request by casey**
This PR is fucking my shit up. For some reason, every value I pass to rotate appears to be an identity transformation. Everything looks right to me, so I must be missing something obvious.

### CODE REVIEW

**Comment by casey** [comment]
I think I wasn't really clearly conceptualizing what I wanted a rotation to do. Probably gotta figure that out before writing the feature.

**Comment by casey** [comment]
I think it might actually be working correctly, it's just a far stranger thing than I imagined.

**Comment by casey** [comment]
output

**Comment by casey** [comment]
output

**Comment by casey** [comment]
Above is `resize:1024:1024 rotate:0.111 for:16 square circle loop save`

**Comment by casey** [comment]
The thing that's strange is that setting a rotation applies it on every future transformation.

**Comment by casey** [comment]
¡Ahora estamos cocinando con gas!

output

**Comment by casey** [comment]
output

**Comment by casey** [comment]
The tests are working now, but what I implemented might not actually be very useful.

`rotate` takes one argument, which is an angle in [turns](https://en.wikipedia.org/wiki/Turn_(angle)). It sets a rotation on the state. This rotation is used to transform the sampling coordinates every time a filter is applied.

This works, but it's a but it's weird. A lot of the time you don't really want to combine it with a filter, you just want to do something like:

`rotate:0.1 all rotate:-0.1`

I.e. apply the rotation once but don't keep it for future filters.

**Comment by casey** [comment]
Okay, last push for the evening. This makes rotate, I think, more intuitive. The transformation is now applied before filtering, and the filter acts on transformed coordinates. I'm not sure if this is better or not, but now you can do `rotate:0.125 square` and get a square rotated 45 degrees.

**Comment by casey** [comment]
Scale is gonna be lit, btw.

**Review by terror — APPROVED** [review]

**Pull request merged**
