### PR TITLE
Support tilde in save, load and open

### PR DESCRIPTION
**Pull request by terror**
#117 

Needs test?

### CODE REVIEW

**Comment by terror** [comment]
> Ahhhhh, yeah, it should probably have a test. I can't figure out how to write one though. Any ideas?

Since we can use `open` to print out the path (by setting the open command to echo), we can set `$HOME` to `.` and just expect that the printed path contains that prefix

**Comment by casey** [comment]
That would work for open, but not for save and load. Why don't we set $HOME
to the path to the tempdir, and then assert that it saved to a file in the
tempdir, loaded from the same file, etc?

**Comment by terror** [comment]
> That would work for open, but not for save and load. Why don't we set $HOME
> to the path to the tempdir, and then assert that it saved to a file in the
> tempdir, loaded from the same file, etc?
> 

Yeah we could do that, I just assumed testing one would suffice since they're all calling the same method

**Comment by casey** [comment]
Yeah, good point. I would say we should test with all of them, since we could easily forget to do tilde expansion for any of them.

**Comment by casey** [comment]
Reviewing the code, I think that there's probably a better way to solve this problem than to expand tilde ourselves.

The whole reason I wanted this in the first place was to be able to write: `save:~/foo.png` which doesn't work, because the shell won't expand `~` unless it's the first character in a word.

I'm thinking that instead we should actually improve parsing so that you can write:

```
save: ~/foo.png
```

This would allow the shell to expand the tilde, instead of us.

The downsides of doing it ourselves:
- New dependency
- For every command that takes a path, we need to remember to shell expand, and if we don't, we'll have the bug that `~` doesn't get expanded for that particular command
- The `shellexpand` library might implement slightly different semantics from the user's shell
- We can no longer take non-unicode paths

I actually think this would be pretty easy, we just need to do a preprocessing step on the command line where we group arguments by `:` and then parse commands from that grouping.

What do you think?

**Pull request closed without merging**
